# Generated by Django 5.1.6 on 2025-03-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_looking_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='looking_for',
            new_name='I_am_looking_for',
        ),
    ]
