# Generated by Django 5.1.6 on 2025-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_looking_for_customuser_i_am_looking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='I_am_looking_for',
        ),
    ]
