# Generated by Django 5.1.6 on 2025-03-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_i_am_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='I_am_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
