# Generated by Django 5.1.6 on 2025-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_i_am_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='I_am_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='Other_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience_in_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='password1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='password2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
