# Generated by Django 5.1.6 on 2025-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_user_workerprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoporindividualprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='shoporindividualprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='shoporindividualprofile',
            name='individual_name',
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='password1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='password2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoporindividualprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
