# Generated by Django 5.1.6 on 2025-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_user_shoporindividualprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoporindividualprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='shoporindividualprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='shoporindividualprofile',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='password2',
        ),
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='user_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('individual', 'Individual')], default='shop', max_length=20),
        ),
    ]
