# Generated by Django 5.1.6 on 2025-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_username_shoporindividualprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='Other_skills',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
