# Generated by Django 5.1.6 on 2025-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_workerprofile_other_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='Other_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
