# Generated by Django 5.1.6 on 2025-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_workerprofile_other_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporindividualprofile',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
