# Generated by Django 5.1.6 on 2025-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_shoporindividualprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_in_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
