# Generated by Django 5.1.6 on 2025-03-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
