# Generated by Django 5.1.6 on 2025-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Wname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
